import HeaderSection from '@/components/Home/HeaderSection'
import React from 'react'
import styles from '../topic/[id]/index.module.scss'
import Image from 'next/image'
import PalmTree from '@/svgs/PalmTree'
import Calendar from '@/svgs/Calendar'
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import Link from 'next/link'
import { motion } from 'framer-motion'
import Head from 'next/head'
import { useRouter } from 'next/router'


const SubTopic = ({ dataSubTopic, dataSubCategory, dataStaticWords }) => {
  const router = useRouter();
  const getRandomWidth = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
  const query = router.query.id
  const title = dataSubCategory?.secondaryTopics?.filter((category) => category.id === Number(query))[0]?.name;

  const breakpoints = {
    300: {
      slidesPerView: 2.2,
      spaceBetween: 16,
    },
    400: {
      slidesPerView: 2.2,
      spaceBetween: 16,
    },
    607: {
      slidesPerView: 2.2,
      spaceBetween: 16,
    },
    700: {
      slidesPerView: 2.2,
      spaceBetween: 16,
    },
    1200: {
      slidesPerView: 5,
      spaceBetween: 24,
    },
    1300: {
      slidesPerView: 5,
      spaceBetween: 24,
    },

  }
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <HeaderSection parentName={title} />
      <section id='city_facilities' className={styles.city_facilities} dir={router.locale === 'ar' ? 'rtl' : 'ltr'}>
        <div className="container">
          <div className={styles.sec_container}>
            <motion.div
              initial={{ opacity: 0, x: 100 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 1 }} className={styles.filter_container}>
              <Swiper
                breakpoints={breakpoints}
                dir={router.locale === 'ar' ? 'rtl' : 'ltr'}
                className={styles.swiper_container}
              >

                <SwiperSlide className={styles.swiper_slide_box}>
                  <Link href={`/topic/${dataSubTopic[0]?.parentId}`} scroll={false} className={`${styles.box}`}>
                    <div className={styles.title}>
                      <p>{dataStaticWords.displayAll}</p>
                    </div>
                  </Link >

                </SwiperSlide>

                {dataSubCategory?.secondaryTopics?.map((secTopic, index) =>

                  <SwiperSlide key={index} className={styles.swiper_slide_box}>
                    <Link scroll={false} href={`/subtopic/${secTopic.id}`} className={`${styles.box}  ${Number(query) === secTopic.id && styles.active}`}>
                      <div className={styles.icon_container}>
                        <img src={secTopic.icon} alt={secTopic?.name} />
                      </div>
                      <div className={styles.title}>
                        <p>{secTopic?.name}</p>
                      </div>
                    </Link>
                  </SwiperSlide>


                )}


              </Swiper>
            </motion.div>
            <div className={styles.boxes_container}>
              {dataSubTopic?.map((topic, index) => (
                <motion.div
                  initial={{ opacity: 0, x: -100 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 1 }}

                  key={index}
                  className={styles.box}>
                  <Link href={Number(router.query.id) === 2 ? `/topic-details/${topic.id}` : (Number(router.query.id) === 1 || 13 ? `/subdetails/${topic.id}` : `/details/${topic.id}`)}>
                    <div className={styles.img_container}>
                      <Image src={topic.icon.includes(',') ? topic.icon.split(',')[0] : topic.icon} width={233} height={166} />
                    </div>
                    <div className={styles.title}>
                      <h5>{topic?.name} </h5>

                    </div>

                    <div className={styles.desc}>
                      {topic.translatedDesc}
                    </div>
                  </Link>

                </motion.div>
              ))}

            </div>

            <div className={styles.boxes_container_mobile}>
              {dataSubTopic?.map((topic, index) => (
                <Link href={`/details/${topic.id}`}
                  className={styles.box} key={index}
                  style={{
                    width: `164px`,
                    height: `${getRandomWidth(140, 240)}px`, // Set the height for all boxes
                  }}>
                  <div className={styles.img_container}>
                    {/* <Image src={'/assets/images/place.png'} width={233} height={166} />
                     */}
                    <Image src={topic.icon.includes(',') ? topic.icon.split(',')[0] : topic.icon} layout="fill" objectFit="cover" />

                  </div>
                  <div className={styles.title}>
                    <h5>{topic?.name} </h5>
                  </div>
                </Link>
              ))}
            </div>

          </div>
        </div>

      </section>
    </>
  )
}
export default SubTopic


export async function getStaticPaths() {
  const response = await fetch('https://api.almadinah.io/api/Topics/GetMainTopics?lang=2&ContentSamplesToReturn=0&pagenum=1&pagesize=50');
  const topics = await response.json();

  const paths = topics.map(topic => ({
    params: { id: topic.id.toString() },
  }));

  return { paths, fallback: 'blocking' };
}



export async function getStaticProps({ params, locale }) {
  const languagesConfig = require("../../../public/locales/languagesDetails.json");
  const langId = languagesConfig.filter((lang) => lang.shortCut === locale)[0].id;
  // languagesConfig[locale]?.id ||

  const responseStaticWords = await fetch(`https://api.almadinah.io/api/Settings/GetStaticWords?lang=${langId}`);
  const dataStaticWords = await responseStaticWords.json();

  // Fetch main topics with the initial topicId
  const responseMainTopic = await fetch(`https://api.almadinah.io/api/Contents/GetContents?topicId=${params.id}&lang=${langId}&pagenum=1&pagesize=50&withLatLng=false`);
  const dataMainTopic = await responseMainTopic.json();

  const responseSubCategory = await fetch(`https://api.almadinah.io/api/Topics/GetSubCategories?topicId=${dataMainTopic[0]?.parentId}&lang=${langId}&ContentSamplesToReturn=0&pagenum=1&pagesize=50`);
  const dataSubCategory = await responseSubCategory.json();

  const responseSubTopic = await fetch(`https://api.almadinah.io/api/Contents/GetContents?topicId=${params.id}&lang=${langId}&pagenum=1&pagesize=50&withLatLng=false`);
  const dataSubTopic = await responseSubTopic.json();

  return {
    props: {
      dataMainTopic,
      dataSubTopic,
      dataSubCategory,
      dataStaticWords
    },

    revalidate: 10,
  };




}



