import HederPages from '@/components/HeaderPages'
import VirtualGuide from '@/components/Home/VirtualGuide'
import Navbar from '@/components/Navbar'
import React from 'react'

const VirtualGuidePage = ({ dataContentDetailsGuide, dataStaticWords, dataAllLangs, }) => {

  return (
    <>
      <Head>
        <title>{dataStaticWords.guideVirtua}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <HederPages dataContentDetailsGuide={dataContentDetailsGuide} dataAllLangs={dataAllLangs} parentName={dataStaticWords.guideVirtual} />

      <VirtualGuide dataStaticWords={dataStaticWords} guidData={dataContentDetailsGuide} />

    </>
  )
}

export default VirtualGuidePage


export async function getServerSideProps({ params, locale }) {
  const languagesConfig = require("../../../public/locales/languagesDetails.json");
  const langId = languagesConfig.filter((lang) => lang.shortCut === locale)[0].id;
  // languagesConfig[locale]?.id ||
  const responseAllLangs = await fetch(
    `https://api.almadinah.io/api/Settings/GetAllLanguages?pagenum=1&pagesize=50`
  );
  const dataAllLangs = await responseAllLangs?.json();

  const responseStaticWords = await fetch(`https://api.almadinah.io/api/Settings/GetStaticWords?lang=${langId}`);
  const dataStaticWords = await responseStaticWords.json();

  // Fetch main topics with the initial topicId
  const responseContentDetailsGuide = await fetch(`https://api.almadinah.io/api/Contents/GetContents?topicId=4&lang=${langId}&pagenum=1&pagesize=50&withLatLng=false`);
  const dataContentDetailsGuide = await responseContentDetailsGuide.json();



  return {
    props: {
      dataStaticWords,
      dataAllLangs,
      dataContentDetailsGuide
    },
  };
}
