import HederPages from '@/components/HeaderPages'
import VirtualGuide from '@/components/Home/VirtualGuide'
import Head from 'next/head'
import React from 'react'

const VirtualGuidePage = ({ dataContentDetailsGuide, dataStaticWords, dataAllLangs, dir }) => {

  return (
    <>
      <Head>
        <title>{dataStaticWords.guideVirtua}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <HederPages dir={dir} dataContentDetailsGuide={dataContentDetailsGuide} dataAllLangs={dataAllLangs} parentName={dataStaticWords.guideVirtual} />

      <VirtualGuide dir={dir} dataStaticWords={dataStaticWords} guidData={dataContentDetailsGuide} />

    </>
  )
}

export default VirtualGuidePage


export async function getServerSideProps({ locale }) {
  const languagesConfig = require("../../../public/locales/languagesDetails.json");
  const langId = languagesConfig.filter((lang) => lang.shortCut === locale)[0].id;
  // languagesConfig[locale]?.id ||
  const responseAllLangs = await fetch(
    `https://api.visitmadinahsa.com/api/Settings/GetAllLanguages?pagenum=1&pagesize=50`
  );
  const dataAllLangs = await responseAllLangs?.json();

  const responseStaticWords = await fetch(`https://api.visitmadinahsa.com/api/Settings/GetStaticWords?lang=${langId}`);
  const dataStaticWords = await responseStaticWords.json();

  // Fetch main topics with the initial topicId
  const responseContentDetailsGuide = await fetch(`https://api.visitmadinahsa.com/api/Contents/GetContents?topicId=4&lang=${langId}&pagenum=1&pagesize=50&withLatLng=false`);
  const dataContentDetailsGuide = await responseContentDetailsGuide.json();




  const res = await fetch('https://api.visitmadinahsa.com/api/Settings/GetAllLanguages?pagenum=1&pagesize=50');
  const languages = await res.json();

  const currentLanguage = languages.find(lang => lang.shortCut === locale);
  const dir = currentLanguage?.isRtl ? 'rtl' : 'ltr';


  return {
    props: {
      dataStaticWords,
      dataAllLangs,
      dataContentDetailsGuide,
      dir
    },
  };
}
